@api = http://localhost:3020/api/v1/institutos
@api2 = http://localhost:3020/api/v1/grupos
#@api = http://187.229.22.99:8010/api/v1/institutos
###Apis de la colecion de grupos
@dato = 5
### GET
GET {{api2}}

### GET ITEM
GET {{api2}}/OK/5


### GET ITEM
GET {{api2}}/dato?keyType=OK


### GET ITEM
GET {{api2}}/dato?keyType=BK

//Education
### POST ITEM Grupos
POST {{api2}}
Content-Type: application/json

{
  "IdGrupoOK": "5",
  "IdGrupoBK": "5A-4",
  "IdPeriodoOK": "1",
  "IdInstitutoOK": "1",
  "IdCarreraOK": "1",
  "IdProgramaOK": "1",
  "IdReticulaOK": "1",
  "IdAsignaturaOK": "1",
  "IdPersonaOK": "4",
  "IdRolOK": "3",
  "Grupo": "5A",
  "Capacidad": 25,
  "IdTipoCursoOK": "208",
  "IdTipoGradoAcaOK": "200",
  "IdTipoHorarioOK": "205"
}

### POST ITEM grupos_estatus
POST {{api2}}/POST/GRUPOESTATUS/5
Content-Type: application/json

{
	"IdTipoEstatusOK": "1",
	"Actual": "1",
	"detail_row": {
		"Activo": "1",
		"Borrado": "0",
		"detail_row_reg": [{
			"UsuarioReg": "RAMIREZ REA EDGAR RUBEN"
		}]
	}
}

### PUT ITEM Grupos
PUT {{api2}}/PUT/GRUPO/5
Content-Type: application/json

{
  "IdGrupoBK": "5A-10",
  "IdPeriodoOK": "4",
  "IdInstitutoOK": "40",
  "IdCarreraOK": "4",
  "IdProgramaOK": "4",
  "IdReticulaOK": "4",
  "IdAsignaturaOK": "4",
  "IdPersonaOK": "44",
  "IdRolOK": "34",
  "Grupo": "5B",
  "Capacidad": 50,
  "IdTipoCursoOK": "2080",
  "IdTipoGradoAcaOK": "2000",
  "IdTipoHorarioOK": "2050"
}

### DELETE ITEM Grupos
DELETE  {{api2}}/dato


###Apis de la coleccioin de cat_institutos
### GET
GET {{api}}

### GET ITEM
GET {{api}}/dato


### GET ITEM
GET {{api}}/dato?keyType=OK


### GET ITEM
GET {{api}}/dato?keyType=BK

//Education
### POST ITEM INSTITUTO
POST {{api}}
Content-Type: application/json

{"IdInstitutoOK": "4","IdInstitutoBK": "18DIT0005Z","DesInstituto": "Instituto Tecnológico de Tepic","Alias": "N","Matriz": "Educacion","Giro": "ITT","IdInstitutoSupOK": "1"}

### PUT ITEM INSTITUTO
PUT {{api}}/dato
Content-Type: application/json

    {"IdInstitutoOK" : "4","IdInstitutoBK" : "XXXXXX","DesInstituto" : "Instituto Tecnológico de XXXXX","Matriz" : "X","Giro" : "EducacionXXX","Alias" : "ITTXXX","IdInstitutoSupOK" : "1"}

### DELETE ITEM INSTITUTO
DELETE  {{api2}}/DELETE/GRUPO/5?keyType=OK

### POST ITEM grupos_estatus
POST {{api2}}/POST/GRUPOESTATUS/5
Content-Type: application/json

{
	"IdTipoEstatusOK": "1",
	"IdEstatusOK": "90",
	"Estatus": "1",
	"Actual": "1",
	"detail_row": {
		"Activo": "1",
		"Borrado": "0",
		"detail_row_reg": [{
			"UsuarioReg": "RAMIREZ REA EDGAR RUBEN"
		}]
	}
}

### PUT ITEM grupos_estatus
PUT {{api2}}/PUT/GRUPOESTATUS/5/90
Content-Type: application/json

{
	"IdTipoEstatusOK": "2",
	"IdEstatusOK": "7",
	"Estatus": "4",
	"Actual": "5",
	"detail_row": {
		"Activo": "0",
		"Borrado": "1",
		"detail_row_reg": [{
			"UsuarioReg": "Urabe Mikoto"
		}]
	}
}

### DELETE ITEM grupos_estatus
DELETE  {{api2}}/DELETE/GRUPOESTATUS/5/80



### POST ITEM grupos_horarios
POST {{api2}}/POST/GRUPOHORARIO/5
Content-Type: application/json

{
    "IdDiaOK": "1",
    "IdDiaBK": "LA1-5A-LUN",
    "Dia": "LUNES",
    "Alias": "Monday",
    "HoraEntrada": "19:00",
    "HoraSalida": "20:00",
    "ToleranciaEntrada": 5,
    "ToleranciaSalida": 5,
    "IdEdificioOK": "1",
    "IdEspacioOK": "1",
    "detail_row": {
      "Activo": "S",
      "Borrado": "N",
      "detail_row_reg": [{
        "UsuarioReg": "ERICK RAMIREZ REA 1"
    	}]
  }
}

### PUT ITEM grupos_horarios
PUT {{api2}}/PUT/GRUPOHORARIO/5/19:00
Content-Type: application/json

{
    "IdDiaOK": "1",
    "IdDiaBK": "LA1-5A-LUN",
    "Dia": "LUNES",
    "Alias": "Monday",
    "HoraEntrada": "18:00",
    "HoraSalida": "20:00",
    "ToleranciaEntrada": 5,
    "ToleranciaSalida": 5,
    "IdEdificioOK": "1",
    "IdEspacioOK": "1",
    "detail_row": {
      "Activo": "S",
      "Borrado": "N",
      "detail_row_reg": [{
        "UsuarioReg": "ERICK RAMIREZ REA 2"
    	}]
  }
}

### DELETE ITEM grupos_horarios
DELETE  {{api2}}/DELETE/GRUPOHORARIO/5/18:00

### POST ITEM grupos_personas
POST {{api2}}/POST/GRUPOPERSONAS/5
Content-Type: application/json

{
    "IdPersonaOK": "1",
    "IdRolOK": "2",
    "NumPeriodo": "1",
    "Repite": "N",
    "detail_row": {
      "Activo": "S",
      "Borrado": "N",
      "detail_row_reg": [{
          "UsuarioReg": "Erick Ramirez Rea"
        }]
    }
}

### PUT ITEM grupos_personas
PUT {{api2}}/PUT/GRUPOPERSONAS/5/1
Content-Type: application/json

{
    "IdPersonaOK": "2",
    "IdRolOK": "2",
    "NumPeriodo": "1",
    "Repite": "N",
    "detail_row": {
      "Activo": "S",
      "Borrado": "N",
      "detail_row_reg": [{
          "UsuarioReg": "Juan Antonio Graxiola Quiroz"
        }]
    }
}

### DELETE ITEM grupos_personas
DELETE  {{api2}}/DELETE/GRUPOPERSONAS/5/2



